{% set name = "ruby" %}
{% set version = "3.4.7" %}
{% set major_minor = '.'.join(version.split('.')[0:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cache.ruby-lang.org/pub/{{ name }}/{{ major_minor }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23815a6d095696f7919090fdc3e2f9459b2c83d57224b2e446ce1f5f7333ef36
  patches:
    # Patches/work-arounds for passing make check
    - 0001-Dont-t-add-SDKROOT-to-vals.patch  # [osx]

build:
  number: 0
  track_features:
    - rb{{ major_minor | replace(".", "") }}
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  ignore_run_exports:
    # We need CXX during build time to generate rbconfig.rb
    - libstdcxx-ng

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    # We need CXX during build time to generate rbconfig.rb
    - {{ compiler('cxx') }}
    - gnuconfig                        # [unix]
    - autoconf                         # [unix]
    - automake                         # [unix]
    - libtool                          # [unix]
    - make                             # [unix]
    - pkg-config
    - bison                            # [unix]
    - gperf                            # [unix]
  host:
    - openssl {{ openssl }}
    # libyaml (for psych)
    - yaml {{ yaml }}
    - zlib {{ zlib }}
    - libffi {{ libffi }}
    - readline {{ readline }}          # [unix]
    # need for readline
    - ncurses {{ ncurses }}            # [unix]
    - gettext {{ gettext }}            # [osx]
    - gmp {{ gmp }}                    # [unix]
    # ext/gdbm (old db need for old tests and old projects)
    - gdbm {{ gdbm }}                  # [unix]

  run:
    - gettext       # [osx]
    - libffi >=3.4,<3.5
    - openssl >=3,<4.0a0

test:
  requires:
    - {{ compiler('c') }}
    - make  # [unix]
  files:
    - native/hello.c
    - native/config.rb
  commands:
    - ruby --version
    - gem --version
    - ruby -e 'puts "Hi, from Ruby!"'
    - ruby -r rubygems -e 'puts "Has gems."; exit 0'
    - ruby -r fiddle -r openssl -r yaml -r zlib -e 'puts "Has all dependencies."; exit 0'
    - ruby -r readline -e 'puts "Has readline."; exit 0'  # [unix]

    - ruby -e 'require "openssl"; p OpenSSL::OPENSSL_VERSION'
    - ruby -e 'require "psych"; require "yaml"; p Psych::VERSION'
    - ruby -e 'require "zlib"; p Zlib::ZLIB_VERSION'
    - ruby -e 'require "fiddle"; puts :ok'
    - ruby -e 'require "readline"; puts :ok'  # [unix]

    # Tests it can build libraries with native dependencies
    - cd native                        # [unix]
    - ruby config.rb                   # [unix]
    - make                             # [unix]
    - ruby -r ./hello.so -e 'hello'    # [unix]

about:
  home: https://www.ruby-lang.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: A dynamic, open source programming language with a focus on simplicity and productivity.
  description: |
    A dynamic, open source programming language with a focus on simplicity and productivity.
    It has an elegant syntax that is natural to read and easy to write.
  doc_url: https://www.ruby-lang.org/en/documentation
  dev_url: https://github.com/ruby/ruby

extra:
  recipe-maintainers:
    - scopatz
    - jimmynguyc
    - sodre
    - wolfv
    - xhochy
