{% set name = "ruby" %}
{% set major_minor = "2.5" %}
{% set version = "3.0.0" %}
{% set sha256 = "c3e5cbdf568da965d28c06b04887d87b6d2a25e303471fb4f8c49b0dd754fc01" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cache.ruby-lang.org/pub/ruby/{{ major_minor }}/ruby-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  track_features:
    - rb{{ version | replace(".", "") }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - openssl
    - zlib
    - readline
    - tk
    - yaml
    - gettext  # [osx]
    - libffi   # [osx]
    - gmp

test:
  commands:
    - ruby --version
    - gem --version
    - ruby -e 'puts "Hi, from Ruby!"'
    - ruby -r rubygems -e 'puts "Has gems."; exit 0'
    - ruby -r openssl -r readline -r yaml -r zlib -e 'puts "Has all dependencies."; exit 0'

about:
  home: https://www.ruby-lang.org/
  license: GPL v2
  license_family: GPL
  license_file: COPYING
  summary: 'A dynamic, open source programming language with a focus on simplicity and productivity.'
  description: |
    A dynamic, open source programming language with a focus on simplicity and productivity.
    It has an elegant syntax that is natural to read and easy to write.
  doc_url: https://www.ruby-lang.org/en/documentation/
  dev_url: https://svn.ruby-lang.org/cgi-bin/viewvc.cgi/

extra:
  recipe-maintainers:
    - scopatz
    - jimmynguyc
