travis:
  secure:
    BINSTAR_TOKEN: tijUw5CieI4UU95ElYAMjnf/Vm9HJcrqjmxU5+rN79RwWivuWcdJ8oQ0QT37Y9J374NH6/CCjrh8tATmYUFuaMvbryowuGYksrZ3SPhr/Utkm8jkwoef4ch2c8fkgbvfDhQawTUG8/6wlh8Ogy8o0nIT6d1brVHYRLzY6Ago7U+U8K2dquNroPccaTJb0pzQnnC8iz92G+XEIqmN1Ils5QmeYE7eOY6JI8xXoBG0QqNWvJzzkrs357Fn4r2jJy6ClhKi5fIyv63kd3ma583IHn1SjPDMTuRsBWGJ97GNT1P5YlJzEauYhZ4pqPvl7kKuk2DS0MD4LGMKOJvg2Urkb9ClS4ThhCMTw9vFxUy4o+G9OD9L+B7AL1gGEZ0KeeI25W1EuNWqjuvwjVH+UU1uYXN0bHZV4U1SwVtBKAj0R0bvfwX420QuxyuPp9SQ4/7pXEpMoPdPByIrr+0YaLeYsm/uUPDBJypdnQmGhUCwCFyFbLI9RILCF1L6PQWOg12R1vkh6kVa023/lD3Vus3VRy3pvYfhOIUfKUj1hcdf2wbWFsoXC12h8FdXdHPNf4n0qOESlp1CFdrjF4Xw/0P5ZDr8MsI5dyYM31Z3gOUpwEymXGgJiMcHzZIpOa15CpY6gn9uKy9ZTB0GJvb8fMVT6RzGN3SqQttLE0HrNTV6CVo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
